### ISSUE TITLE
Punchout script still needed?

### ISSUE THREAD

**Issue by JakobMiksch** [iboates/osm-utilities-docker#13]
Hi @iboates is the [punchout.py](https://github.com/iboates/osm-utilities-docker/blob/master/osm2pgsql/punchout.py) script still needed?
 otherwise it could be removed I guess

**Comment by iboates** [comment]
Nope, it's gone in https://github.com/iboates/osm-utilities-docker/commit/f1c383700eb7271ecd4bb9dce0bfae5d233510a6
