### ISSUE TITLE
Look for new releases automatically

### ISSUE THREAD

**Issue by iboates** [iboates/osm-utilities-docker#9]
During the nightly builds, check for more recent releases and then try to build it using the latest Dockerfile as a template

**Comment by JakobMiksch** [comment]
Why is this completed?

**Comment by iboates** [comment]
I meant to just close it instead of marking as completed, but I think this is actually not a good idea. in the latest release (2.0.1), it wouldn't have worked anyway - I originally did just copy the 2.0.0 file and it failed building due to osm2pgsql-gen now being bundled and not built separately. I worry about less obvious breaking changes slipping through.

Incidentally this is a good example of what we talked about a while ago. The reason why we have many different docker files instead of trying to just template a single generic one. The previous dockerfile would have never worked unless you actually `sed`-ed the problematic line right out of it, or doing some hideously ugly boolean hacks like [here](https://stackoverflow.com/questions/43654656/dockerfile-if-else-condition-with-external-arguments).

I'm willing to be convinced though, if you think it really adds value then I will reconsider it, but I would like to then have a more robust test & build pipeline
